/*
CLICK-PASS-API

Testing CardAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package clickapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/iota-uz/click/clickapi"
)

func Test_clickapi_CardAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CardAPIService CreateCardToken", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CardAPI.CreateCardToken(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CardAPIService DeleteCardToken", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serviceId int64
		var cardToken string

		resp, httpRes, err := apiClient.CardAPI.DeleteCardToken(context.Background(), serviceId, cardToken).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CardAPIService VerifyCardToken", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CardAPI.VerifyCardToken(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
