/*
CLICK-PASS-API

API for managing payments and fiscalization with CLICK Pass.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clickapi

import (
	"encoding/json"
)

// checks if the FiscalizationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiscalizationResponse{}

// FiscalizationResponse struct for FiscalizationResponse
type FiscalizationResponse struct {
	// Error code
	ErrorCode *int32 `json:"error_code,omitempty" xml:"error_code"`
	// Error description
	ErrorNote *string `json:"error_note,omitempty" xml:"error_note"`
}

// NewFiscalizationResponse instantiates a new FiscalizationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiscalizationResponse() *FiscalizationResponse {
	this := FiscalizationResponse{}
	return &this
}

// NewFiscalizationResponseWithDefaults instantiates a new FiscalizationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiscalizationResponseWithDefaults() *FiscalizationResponse {
	this := FiscalizationResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *FiscalizationResponse) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode) {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalizationResponse) GetErrorCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *FiscalizationResponse) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *FiscalizationResponse) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetErrorNote returns the ErrorNote field value if set, zero value otherwise.
func (o *FiscalizationResponse) GetErrorNote() string {
	if o == nil || IsNil(o.ErrorNote) {
		var ret string
		return ret
	}
	return *o.ErrorNote
}

// GetErrorNoteOk returns a tuple with the ErrorNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalizationResponse) GetErrorNoteOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorNote) {
		return nil, false
	}
	return o.ErrorNote, true
}

// HasErrorNote returns a boolean if a field has been set.
func (o *FiscalizationResponse) HasErrorNote() bool {
	if o != nil && !IsNil(o.ErrorNote) {
		return true
	}

	return false
}

// SetErrorNote gets a reference to the given string and assigns it to the ErrorNote field.
func (o *FiscalizationResponse) SetErrorNote(v string) {
	o.ErrorNote = &v
}

func (o FiscalizationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiscalizationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["error_code"] = o.ErrorCode
	}
	if !IsNil(o.ErrorNote) {
		toSerialize["error_note"] = o.ErrorNote
	}
	return toSerialize, nil
}

type NullableFiscalizationResponse struct {
	value *FiscalizationResponse
	isSet bool
}

func (v NullableFiscalizationResponse) Get() *FiscalizationResponse {
	return v.value
}

func (v *NullableFiscalizationResponse) Set(val *FiscalizationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFiscalizationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFiscalizationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiscalizationResponse(val *FiscalizationResponse) *NullableFiscalizationResponse {
	return &NullableFiscalizationResponse{value: val, isSet: true}
}

func (v NullableFiscalizationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiscalizationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


