/*
CLICK-PASS-API

API for managing payments and fiscalization with CLICK Pass.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clickapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CompleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompleteRequest{}

// CompleteRequest Request parameters for the Complete stage (action = 1). Used to finalize the payment.
type CompleteRequest struct {
	// Payment ID in CLICK system.
	ClickTransId int64 `form:"click_trans_id" json:"click_trans_id"` // Payment ID in CLICK system.
	// ID of the service.
	ServiceId int32 `form:"service_id" json:"service_id"` // ID of the service.
	// Payment number in CLICK system. Shown in SMS to customer.
	ClickPaydocId int64 `form:"click_paydoc_id" json:"click_paydoc_id"` // Payment number in CLICK system. Shown in SMS to customer.
	// Order ID / personal account / login in the supplier billing system.
	MerchantTransId string `form:"merchant_trans_id" json:"merchant_trans_id"` // Order ID / personal account / login in the supplier billing system.
	// Payment ID received during Prepare stage for confirmation.
	MerchantPrepareId int32 `form:"merchant_prepare_id" json:"merchant_prepare_id"` // Payment ID received during Prepare stage for confirmation.
	// Payment amount (in soums).
	Amount float32 `form:"amount" json:"amount"` // Payment amount (in soums).
	// Action to perform. 1 – for Complete stage.
	Action int32 `form:"action" json:"action"` // Action to perform. 1 – for Complete stage.
	// Status code for completion of payment. 0 – success. Otherwise, an error code.
	Error int32 `form:"error" json:"error"` // Status code for completion of payment. 0 – success. Otherwise, an error code.
	// Description of the error code or result.
	ErrorNote string `form:"error_note" json:"error_note"` // Description of the error code or result.
	// Payment date in format: 'YYYY-MM-DD HH:mm:ss'.
	SignTime string `form:"sign_time" json:"sign_time"` // Payment date in format: &#39;YYYY-MM-DD HH:mm:ss&#39;.
	// Verification string. MD5 hash of: click_trans_id + service_id + SECRET_KEY + merchant_trans_id + merchant_prepare_id + amount + action + sign_time.
	SignString string `form:"sign_string" json:"sign_string"` // Verification string. MD5 hash of: click_trans_id + service_id + SECRET_KEY + merchant_trans_id + merchant_prepare_id + amount + action + sign_time.
}

type _CompleteRequest CompleteRequest

// NewCompleteRequest instantiates a new CompleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompleteRequest(clickTransId int64, serviceId int32, clickPaydocId int64, merchantTransId string, merchantPrepareId int32, amount float32, action int32, error_ int32, errorNote string, signTime string, signString string) *CompleteRequest {
	this := CompleteRequest{}
	this.ClickTransId = clickTransId
	this.ServiceId = serviceId
	this.ClickPaydocId = clickPaydocId
	this.MerchantTransId = merchantTransId
	this.MerchantPrepareId = merchantPrepareId
	this.Amount = amount
	this.Action = action
	this.Error = error_
	this.ErrorNote = errorNote
	this.SignTime = signTime
	this.SignString = signString
	return &this
}

// NewCompleteRequestWithDefaults instantiates a new CompleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompleteRequestWithDefaults() *CompleteRequest {
	this := CompleteRequest{}
	return &this
}

// GetClickTransId returns the ClickTransId field value
func (o *CompleteRequest) GetClickTransId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ClickTransId
}

// GetClickTransIdOk returns a tuple with the ClickTransId field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetClickTransIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClickTransId, true
}

// SetClickTransId sets field value
func (o *CompleteRequest) SetClickTransId(v int64) {
	o.ClickTransId = v
}

// GetServiceId returns the ServiceId field value
func (o *CompleteRequest) GetServiceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *CompleteRequest) SetServiceId(v int32) {
	o.ServiceId = v
}

// GetClickPaydocId returns the ClickPaydocId field value
func (o *CompleteRequest) GetClickPaydocId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ClickPaydocId
}

// GetClickPaydocIdOk returns a tuple with the ClickPaydocId field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetClickPaydocIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClickPaydocId, true
}

// SetClickPaydocId sets field value
func (o *CompleteRequest) SetClickPaydocId(v int64) {
	o.ClickPaydocId = v
}

// GetMerchantTransId returns the MerchantTransId field value
func (o *CompleteRequest) GetMerchantTransId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantTransId
}

// GetMerchantTransIdOk returns a tuple with the MerchantTransId field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetMerchantTransIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantTransId, true
}

// SetMerchantTransId sets field value
func (o *CompleteRequest) SetMerchantTransId(v string) {
	o.MerchantTransId = v
}

// GetMerchantPrepareId returns the MerchantPrepareId field value
func (o *CompleteRequest) GetMerchantPrepareId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MerchantPrepareId
}

// GetMerchantPrepareIdOk returns a tuple with the MerchantPrepareId field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetMerchantPrepareIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantPrepareId, true
}

// SetMerchantPrepareId sets field value
func (o *CompleteRequest) SetMerchantPrepareId(v int32) {
	o.MerchantPrepareId = v
}

// GetAmount returns the Amount field value
func (o *CompleteRequest) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CompleteRequest) SetAmount(v float32) {
	o.Amount = v
}

// GetAction returns the Action field value
func (o *CompleteRequest) GetAction() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetActionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CompleteRequest) SetAction(v int32) {
	o.Action = v
}

// GetError returns the Error field value
func (o *CompleteRequest) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *CompleteRequest) SetError(v int32) {
	o.Error = v
}

// GetErrorNote returns the ErrorNote field value
func (o *CompleteRequest) GetErrorNote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorNote
}

// GetErrorNoteOk returns a tuple with the ErrorNote field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetErrorNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorNote, true
}

// SetErrorNote sets field value
func (o *CompleteRequest) SetErrorNote(v string) {
	o.ErrorNote = v
}

// GetSignTime returns the SignTime field value
func (o *CompleteRequest) GetSignTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignTime
}

// GetSignTimeOk returns a tuple with the SignTime field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetSignTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignTime, true
}

// SetSignTime sets field value
func (o *CompleteRequest) SetSignTime(v string) {
	o.SignTime = v
}

// GetSignString returns the SignString field value
func (o *CompleteRequest) GetSignString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignString
}

// GetSignStringOk returns a tuple with the SignString field value
// and a boolean to check if the value has been set.
func (o *CompleteRequest) GetSignStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignString, true
}

// SetSignString sets field value
func (o *CompleteRequest) SetSignString(v string) {
	o.SignString = v
}

func (o CompleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["click_trans_id"] = o.ClickTransId
	toSerialize["service_id"] = o.ServiceId
	toSerialize["click_paydoc_id"] = o.ClickPaydocId
	toSerialize["merchant_trans_id"] = o.MerchantTransId
	toSerialize["merchant_prepare_id"] = o.MerchantPrepareId
	toSerialize["amount"] = o.Amount
	toSerialize["action"] = o.Action
	toSerialize["error"] = o.Error
	toSerialize["error_note"] = o.ErrorNote
	toSerialize["sign_time"] = o.SignTime
	toSerialize["sign_string"] = o.SignString
	return toSerialize, nil
}

func (o *CompleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"click_trans_id",
		"service_id",
		"click_paydoc_id",
		"merchant_trans_id",
		"merchant_prepare_id",
		"amount",
		"action",
		"error",
		"error_note",
		"sign_time",
		"sign_string",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompleteRequest := _CompleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompleteRequest)

	if err != nil {
		return err
	}

	*o = CompleteRequest(varCompleteRequest)

	return err
}

type NullableCompleteRequest struct {
	value *CompleteRequest
	isSet bool
}

func (v NullableCompleteRequest) Get() *CompleteRequest {
	return v.value
}

func (v *NullableCompleteRequest) Set(val *CompleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompleteRequest(val *CompleteRequest) *NullableCompleteRequest {
	return &NullableCompleteRequest{value: val, isSet: true}
}

func (v NullableCompleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
