/*
CLICK-PASS-API

API for managing payments and fiscalization with CLICK Pass.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clickapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FiscalQRCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiscalQRCodeRequest{}

// FiscalQRCodeRequest struct for FiscalQRCodeRequest
type FiscalQRCodeRequest struct {
	// Service ID
	ServiceId int64 `json:"service_id" xml:"service_id"`
	// Payment Identifier
	PaymentId int64 `json:"payment_id" xml:"payment_id"`
	// Check URL
	Qrcode string `json:"qrcode" xml:"qrcode"`
}

type _FiscalQRCodeRequest FiscalQRCodeRequest

// NewFiscalQRCodeRequest instantiates a new FiscalQRCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiscalQRCodeRequest(serviceId int64, paymentId int64, qrcode string) *FiscalQRCodeRequest {
	this := FiscalQRCodeRequest{}
	this.ServiceId = serviceId
	this.PaymentId = paymentId
	this.Qrcode = qrcode
	return &this
}

// NewFiscalQRCodeRequestWithDefaults instantiates a new FiscalQRCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiscalQRCodeRequestWithDefaults() *FiscalQRCodeRequest {
	this := FiscalQRCodeRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *FiscalQRCodeRequest) GetServiceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *FiscalQRCodeRequest) GetServiceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *FiscalQRCodeRequest) SetServiceId(v int64) {
	o.ServiceId = v
}

// GetPaymentId returns the PaymentId field value
func (o *FiscalQRCodeRequest) GetPaymentId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
func (o *FiscalQRCodeRequest) GetPaymentIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentId, true
}

// SetPaymentId sets field value
func (o *FiscalQRCodeRequest) SetPaymentId(v int64) {
	o.PaymentId = v
}

// GetQrcode returns the Qrcode field value
func (o *FiscalQRCodeRequest) GetQrcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Qrcode
}

// GetQrcodeOk returns a tuple with the Qrcode field value
// and a boolean to check if the value has been set.
func (o *FiscalQRCodeRequest) GetQrcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Qrcode, true
}

// SetQrcode sets field value
func (o *FiscalQRCodeRequest) SetQrcode(v string) {
	o.Qrcode = v
}

func (o FiscalQRCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiscalQRCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["payment_id"] = o.PaymentId
	toSerialize["qrcode"] = o.Qrcode
	return toSerialize, nil
}

func (o *FiscalQRCodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"payment_id",
		"qrcode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFiscalQRCodeRequest := _FiscalQRCodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFiscalQRCodeRequest)

	if err != nil {
		return err
	}

	*o = FiscalQRCodeRequest(varFiscalQRCodeRequest)

	return err
}

type NullableFiscalQRCodeRequest struct {
	value *FiscalQRCodeRequest
	isSet bool
}

func (v NullableFiscalQRCodeRequest) Get() *FiscalQRCodeRequest {
	return v.value
}

func (v *NullableFiscalQRCodeRequest) Set(val *FiscalQRCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFiscalQRCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFiscalQRCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiscalQRCodeRequest(val *FiscalQRCodeRequest) *NullableFiscalQRCodeRequest {
	return &NullableFiscalQRCodeRequest{value: val, isSet: true}
}

func (v NullableFiscalQRCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiscalQRCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


