/*
CLICK-PASS-API

API for managing payments and fiscalization with CLICK Pass.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clickapi

import (
	"encoding/json"
)

// checks if the CardTokenVerifyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardTokenVerifyResponse{}

// CardTokenVerifyResponse struct for CardTokenVerifyResponse
type CardTokenVerifyResponse struct {
	// Error code
	ErrorCode *int32 `json:"error_code,omitempty"`
	// Error description
	ErrorNote *string `json:"error_note,omitempty"`
	// Card number
	CardNumber *string `json:"card_number,omitempty"`
}

// NewCardTokenVerifyResponse instantiates a new CardTokenVerifyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardTokenVerifyResponse() *CardTokenVerifyResponse {
	this := CardTokenVerifyResponse{}
	return &this
}

// NewCardTokenVerifyResponseWithDefaults instantiates a new CardTokenVerifyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardTokenVerifyResponseWithDefaults() *CardTokenVerifyResponse {
	this := CardTokenVerifyResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *CardTokenVerifyResponse) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode) {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardTokenVerifyResponse) GetErrorCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *CardTokenVerifyResponse) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *CardTokenVerifyResponse) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetErrorNote returns the ErrorNote field value if set, zero value otherwise.
func (o *CardTokenVerifyResponse) GetErrorNote() string {
	if o == nil || IsNil(o.ErrorNote) {
		var ret string
		return ret
	}
	return *o.ErrorNote
}

// GetErrorNoteOk returns a tuple with the ErrorNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardTokenVerifyResponse) GetErrorNoteOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorNote) {
		return nil, false
	}
	return o.ErrorNote, true
}

// HasErrorNote returns a boolean if a field has been set.
func (o *CardTokenVerifyResponse) HasErrorNote() bool {
	if o != nil && !IsNil(o.ErrorNote) {
		return true
	}

	return false
}

// SetErrorNote gets a reference to the given string and assigns it to the ErrorNote field.
func (o *CardTokenVerifyResponse) SetErrorNote(v string) {
	o.ErrorNote = &v
}

// GetCardNumber returns the CardNumber field value if set, zero value otherwise.
func (o *CardTokenVerifyResponse) GetCardNumber() string {
	if o == nil || IsNil(o.CardNumber) {
		var ret string
		return ret
	}
	return *o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardTokenVerifyResponse) GetCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CardNumber) {
		return nil, false
	}
	return o.CardNumber, true
}

// HasCardNumber returns a boolean if a field has been set.
func (o *CardTokenVerifyResponse) HasCardNumber() bool {
	if o != nil && !IsNil(o.CardNumber) {
		return true
	}

	return false
}

// SetCardNumber gets a reference to the given string and assigns it to the CardNumber field.
func (o *CardTokenVerifyResponse) SetCardNumber(v string) {
	o.CardNumber = &v
}

func (o CardTokenVerifyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardTokenVerifyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["error_code"] = o.ErrorCode
	}
	if !IsNil(o.ErrorNote) {
		toSerialize["error_note"] = o.ErrorNote
	}
	if !IsNil(o.CardNumber) {
		toSerialize["card_number"] = o.CardNumber
	}
	return toSerialize, nil
}

type NullableCardTokenVerifyResponse struct {
	value *CardTokenVerifyResponse
	isSet bool
}

func (v NullableCardTokenVerifyResponse) Get() *CardTokenVerifyResponse {
	return v.value
}

func (v *NullableCardTokenVerifyResponse) Set(val *CardTokenVerifyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCardTokenVerifyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCardTokenVerifyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardTokenVerifyResponse(val *CardTokenVerifyResponse) *NullableCardTokenVerifyResponse {
	return &NullableCardTokenVerifyResponse{value: val, isSet: true}
}

func (v NullableCardTokenVerifyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardTokenVerifyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


